import Link from "next/link";
import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui";

export function CompanyCard({ company }: { company: { name: string; slug: string; _count?: { experiences: number } } }) { return <Link href={`/companies/${company.slug}`} className="group"><Card className="h-full transition-colors group-hover:border-primary/50"><CardHeader><CardTitle>{company.name}</CardTitle><CardDescription>{company._count?.experiences ?? 0} {company._count?.experiences === 1 ? "experience" : "experiences"}</CardDescription></CardHeader></Card></Link>; }

export function VerdictBadge({ verdict }: { verdict: string | null | undefined }) { if (!verdict) return null; const normalized = verdict.toLowerCase(); return <Badge variant={normalized.includes("select") || normalized.includes("offer") ? "success" : normalized.includes("reject") ? "danger" : "warning"}>{verdict}</Badge>; }

export function ExperienceMetadata({ degree, roleTitle, graduationYear, rounds }: { degree: string; roleTitle: string; graduationYear: number; rounds: number }) { return <div className="flex flex-wrap gap-x-3 gap-y-1 text-sm text-muted-foreground"><span>{degree}</span><span aria-hidden="true">·</span><span>{roleTitle}</span><span aria-hidden="true">·</span><span>{graduationYear}</span><span aria-hidden="true">·</span><span>{rounds} {rounds === 1 ? "round" : "rounds"}</span></div>; }

export function ExperienceCard({ experience }: { experience: { id: string; company: { name: string }; degree: string; roleTitle: string; graduationYear: number; rounds: { id: string }[]; verdict?: string | null } }) { return <Card className="h-full"><CardHeader><div className="flex items-start justify-between gap-4"><div><CardDescription className="mb-2">{experience.company.name}</CardDescription><CardTitle>{experience.roleTitle}</CardTitle></div><VerdictBadge verdict={experience.verdict} /></div></CardHeader><CardContent><ExperienceMetadata degree={experience.degree} roleTitle={experience.roleTitle} graduationYear={experience.graduationYear} rounds={experience.rounds.length} /><Link href={`/experiences/${experience.id}`} className="mt-5 inline-block text-sm font-semibold text-primary hover:underline">Read experience →</Link></CardContent></Card>; }

export function InterviewRoundTimeline({ rounds }: { rounds: { title?: string | null; name?: string | null; description?: string | null }[] }) { return <div className="flex flex-col">{rounds.map((round, index) => <div key={`${round.title ?? round.name ?? "round"}-${index}`} className="relative flex gap-4 pb-8 last:pb-0"><div className="flex flex-col items-center"><span className="z-1 flex size-8 shrink-0 items-center justify-center rounded-full border border-primary bg-background font-mono text-xs font-bold text-primary">{String(index + 1).padStart(2, "0")}</span>{index < rounds.length - 1 && <span className="w-px grow bg-border" />}</div><div className="pt-1"><h3 className="font-semibold">{round.title ?? round.name ?? `Round ${index + 1}`}</h3>{round.description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{round.description}</p>}</div></div>)}</div>; }

export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-lg border border-dashed border-border bg-muted/30 px-6 py-12 text-center"><h3 className="font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{description}</p></div>; }
